<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.we0j</groupId>
        <artifactId>we0j-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>
    <artifactId>we0j-agent</artifactId>
    <name>we0j-agent</name>
    <dependencies>
        <dependency>
            <groupId>com.we0j</groupId>
            <artifactId>we0j-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.we0j</groupId>
            <artifactId>we0j-infra</artifactId>
        </dependency>
        <dependency>
            <groupId>com.we0j</groupId>
            <artifactId>we0j-llm</artifactId>
        </dependency>
        <dependency>
            <groupId>com.we0j</groupId>
            <artifactId>we0j-tool</artifactId>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
        </dependency>
    </dependencies>
</project>
